### ISSUE TITLE
Error: spawn EMFILE

### ISSUE THREAD

**Issue by hemanth** [bangalorejs/sambar#3]
```
$ ./bin/sambar -c examples/bangaloreJS -t templates/bangaloreJS -o site


   bye

child_process.js:927
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn EMFILE
    at errnoException (child_process.js:980:11)
    at ChildProcess.spawn (child_process.js:927:11)
    at exports.spawn (child_process.js:715:9)
    at gm._spawn (/Users/hemanth/labs/sambar/node_modules/gm/lib/command.js:179:16)
    at gm._exec (/Users/hemanth/labs/sambar/node_modules/gm/lib/command.js:160:17)
    at gm.identify (/Users/hemanth/labs/sambar/node_modules/gm/lib/getters.js:74:10)
    at /Users/hemanth/labs/sambar/bin/sambar:156:19
    at /Users/hemanth/labs/sambar/node_modules/async/lib/async.js:454:21
    at /Users/hemanth/labs/sambar/node_modules/async/lib/async.js:185:13
    at /Users/hemanth/labs/sambar/node_modules/async/lib/async.js:86:13
hemanth at bjs in ~/labs/sambar on master*
```

Getting this error with `node -v // v0.10.22` but site dir has the required content.

**Comment by hemanth** [comment]
@jonmaim meow?
